USE [master]
GO
/****** Object:  Database [TestCustomerDB]    Script Date: 17.09.2022 15:25:49 ******/
CREATE DATABASE [TestCustomerDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestCustomerDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestCustomerDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestCustomerDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestCustomerDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TestCustomerDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestCustomerDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TestCustomerDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TestCustomerDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TestCustomerDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TestCustomerDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TestCustomerDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TestCustomerDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestCustomerDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestCustomerDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestCustomerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestCustomerDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TestCustomerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TestCustomerDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestCustomerDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TestCustomerDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestCustomerDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestCustomerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestCustomerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestCustomerDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TestCustomerDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TestCustomerDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestCustomerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestCustomerDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TestCustomerDB] SET RECOVERY FULL 
GO
ALTER DATABASE [TestCustomerDB] SET  MULTI_USER 
GO
ALTER DATABASE [TestCustomerDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestCustomerDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TestCustomerDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TestCustomerDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TestCustomerDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TestCustomerDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TestCustomerDB', N'ON'
GO
ALTER DATABASE [TestCustomerDB] SET QUERY_STORE = OFF
GO
USE [TestCustomerDB]
GO
/****** Object:  Table [dbo].[Code_lookup_table]    Script Date: 17.09.2022 15:25:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Code_lookup_table](
	[Code_ID] [int] NOT NULL,
	[Code_name] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Code_lookup_table] PRIMARY KEY CLUSTERED 
(
	[Code_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InputData_table]    Script Date: 17.09.2022 15:25:50 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InputData_table](
	[CustomerId] [int] NOT NULL,
	[CustomerName] [varchar](20) NOT NULL,
	[Notes] [varchar](200) NULL,
	[CodeId] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[InputData_table]  WITH CHECK ADD  CONSTRAINT [FK_CodeInput] FOREIGN KEY([CodeId])
REFERENCES [dbo].[Code_lookup_table] ([Code_ID])
GO
ALTER TABLE [dbo].[InputData_table] CHECK CONSTRAINT [FK_CodeInput]
GO
USE [master]
GO
ALTER DATABASE [TestCustomerDB] SET  READ_WRITE 
GO
